### ISSUE TITLE
ссылка на неразрешенный внешний символ

### ISSUE THREAD

**Issue by VIRalZah** [user95401/curly-eureka#1]
main.obj : error LNK2019: ссылка на неразрешенный внешний символ "class cocos2d::CCSprite * __cdecl ModUtils::createSpr
iteOrPlaceholder(char const *)" (?createSpriteOrPlaceholder@ModUtils@@YAPAVCCSprite@cocos2d@@PBD@Z) в функции "bool __f
astcall MenuLayer_init(class gd::MenuLayer *)" (?MenuLayer_init@@YI_NPAVMenuLayer@gd@@@Z). [D:\GDMods\build\just_a_test
.vcxproj]
main.obj : error LNK2019: ссылка на неразрешенный внешний символ "bool __cdecl ModUtils::write_bytes(unsigned int,class
 std::vector<unsigned char,class std::allocator<unsigned char> > const &)" (?write_bytes@ModUtils@@YA_NIABV?$vector@EV?
$allocator@E@std@@@std@@@Z) в функции "unsigned long __stdcall thread_func(void *)" (?thread_func@@YGKPAX@Z). [D:\GDMod
s\build\just_a_test.vcxproj]
D:\GDMods\build\Release\just_a_test.dll : fatal error LNK1120: неразрешенных внешних элементов: 2 [D:\GDMods\build\just
_a_test.vcxproj] some russian

**Comment by user95401** [comment]
sooo curly-eureka folder installed on D:\curly-eureka ?

**Comment by user95401** [comment]
send CMakeLists screenshot

**Comment by VIRalZah** [comment]
can we speak russian?

**Comment by user95401** [comment]
да

**Comment by VIRalZah** [comment]
понял
![image](https://user-images.githubusercontent.com/129858326/229786384-3b197c5f-f1c7-4eec-b5d5-6cdbfbe4d026.png)

**Comment by VIRalZah** [comment]
ничего не понимаю

**Comment by user95401** [comment]
в пути ошибка 
![image](https://user-images.githubusercontent.com/90561697/229786554-a36cb8e3-f5f2-4e65-8484-14210729ec2f.png)

**Comment by VIRalZah** [comment]
а понял спс!

**Comment by VIRalZah** [comment]
Да

**Comment by user95401** [comment]
ну закрываю тогда
