### ISSUE TITLE
But why...

### ISSUE THREAD

**Issue by TheSillyDoggo** [user95401/curly-eureka#4]
Why not just use geode and if an address doesn't exist just custom hook it with geode. Why are you doing this instead of just using geode?

**Comment by user95401** [comment]
what
![image](https://github.com/user95401/curly-eureka/assets/90561697/ee31cbe7-80fe-4d1b-bf96-e7828c1d2d39)
i dont understood

**Comment by user95401** [comment]
a mod that will use these tools in full will be completely independent
even minhook dll

**Comment by TheSillyDoggo** [comment]
When you use minhook. It breaks other mods hooks. Geode solves that

**Comment by user95401** [comment]
u wrong, actually
creation hooks at same time as in other dll will break hook one of these

**Comment by TheSillyDoggo** [comment]
Ok but... What advantage does this have over $modify

**Comment by user95401** [comment]
its dont needed Geode Loader

**Comment by user95401** [comment]
and anything else
