### ISSUE TITLE
ImGUI and hooks

### ISSUE THREAD

**Issue by GarminBro** [user95401/curly-eureka#5]
is building and running ImGUI the best way to get hooks for the game? if not, what is the best way to utilize the hooksutils to get hooks? im new to independent modding and im curious about hooks.

**Comment by user95401** [comment]
what u mean by getting hooks with ImGUI lol
its pretty delusional
maybe u mean getting address for hook with cocos-explorer?

**Comment by user95401** [comment]
u need rva address at game module
because global address in all process never will be same again and again
so u need use module address (gd::base) + rva address (address that relative to game module) as target of hook

aand i use that to find stuff: https://x64dbg.com/

**Comment by GarminBro** [comment]
so you use the module address + the rva to hook the function? i understand that the global addresses change with every process, but the addresses for the hooks are the same every time. if i understand, you use the module + rva adress as the target for the hook in the debugger and thats how u find the functions they hook?

**Comment by GarminBro** [comment]
sorry for the all the questions, hooks are a very unfamiliar concept to me

**Comment by user95401** [comment]
addresses for the hooks isn't same, we calculating that with (game module) + (offset for function in that module)
i use debugger to get that rva (literally button to copy RVA)

**Comment by GarminBro** [comment]
ohhhhh i totally see now, thank you the module changes every time, but the rva doesnt, which is why the hooks are presented as module + rva. that makes sense after thinking about it, thank you
